#!/usr/bin/env bash
# Loop 1-10: prints "bad luck" for 4, "good luck" for 8, "Best School" for others
i=1
while (( i <= 10 ))
do
    if (( i == 4 ))
    then
        echo "bad luck"
    elif (( i == 8 ))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( i++ ))
done
