#!/usr/bin/env bash
# Loop 1-20 with special cases for superstitious numbers
i=1
while (( i <= 20 ))
do
    case $i in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo "number: $i"
            ;;
    esac
    (( i++ ))
done
