#!/usr/bin/env bash
# Checks if specific files exist and check if they are empty
for file in school best_school school_is_amazing
do
    if [ -e "$file" ]
    then
        echo "$file exists"
        if [ -s "$file" ]
        then
            echo "$file is not empty"
        else
            echo "$file is empty"
        fi
    else
        echo "$file does not exist"
    fi
done
