#!/usr/bin/env bash
# Checks if specific files exist, are regular files, and are empty
for file in school best_school school_is_amazing
do
    if [ -e "$file" ]
    then
        echo "$file file exists"
        if [ -f "$file" ]
        then
            echo "$file file is a regular file"
        fi
        if [ -s "$file" ]
        then
            echo "$file file is not empty"
        else
            echo "$file file is empty"
        fi
    else
        echo "$file file does not exist"
    fi
done
